# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: ./

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      github: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Spring settings
spring:
  profiles:
    active: dev

# Table store settings
tablestore:
  endPoint: yourendpoint
  accessKeyId: youraccesskeyid
  accessKeySecret: youraccesskeysecret
  instanceName: yourinstancename
